# Generated by Django 4.2 on 2024-12-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('course', models.CharField(choices=[('frontend', 'FRONTEND DEVELOPER'), ('backend', 'BACKEND DEVELOPER'), ('web_design', 'GRAPHIC DESIGN')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'certificates',
            },
        ),
    ]
